name: FreeBSD Build

on:
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - release: "14.3"
          arch: amd64
          arch_name: amd64
          name: freebsd-amd64
        - release: "14.3"
          arch: aarch64
          arch_name: arm64
          name: freebsd-arm64

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build in FreeBSD VM
      id: freebsd_build
      uses: vmactions/freebsd-vm@v1.2.1
      with:
        release: ${{ matrix.release }}
        arch: ${{ matrix.arch }}
        usesh: true
        sync: sshfs
        prepare: |
          pkg install -y cmake git ninja pkgconf zenity gtk4

        run: |
          git clone --branch v1.23 --depth 1 https://github.com/ring-lang/ring.git ring
          cd ring
          export RING=$(pwd)
          cd language
          cmake . -DCMAKE_BUILD_TYPE=Release -GNinja
          ninja install
          cd ../..
          rm -rf lib
          cmake . -DCMAKE_BUILD_TYPE=Release -GNinja
          ninja

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: toml-${{ matrix.name }}
        path: lib
